name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild build \
            -scheme FellohPaymentSDK \
            -destination 'generic/platform=iOS Simulator' \
            -skipPackagePluginValidation

      - name: Test
        run: |
          xcodebuild test \
            -scheme FellohPaymentSDK \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
            -skipPackagePluginValidation
